# env_manager.py
class EnvManager:
    def read_from_string(self, content):
        
        for line in lines:
            line = line.strip()
            # 跳过空行和注释
            if not line or line.startswith('#'):
                continue
            
            # 按=号分割，取第一个=号
            if '=' in line:
                key, value = line.split('=', 1)
                env_dict[key.strip()] = value.strip()
        
        return env_dict



class EnvManager:
    def read_from_string(self, content):
        """从字符串读取.env 内容并解析为字典"""
        lines = content.strip().split('\n')
        env_dict = {}

        for line in lines:
            line = line.strip()
            # 跳过空行和注释
            if not line or line.startswith('#'):
                continue
            
            # 按=号分割，取第一个=号
            if '=' in line:
                key, value = line.split('=', 1)
                env_dict[key.strip()] = value.strip()
        
        return env_dict
    
    def read_from_file(self, filepath):
        """从文件读取.env 内容"""
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
        return self.read_from_string(content)
    
    def export_to_string(self, env_dict):
        """将环境变量字典导出为字符串格式"""
        lines = []
        for key in sorted(env_dict.keys()):
            value = env_dict[key]
            lines.append(f'{key}={value}')
        
        if lines:
            return '\n'.join(lines) + '\n'
        return ''
    
    def export_to_file(self, filepath, env_dict):
        """将环境变量导出到文件"""
        content = self.export_to_string(env_dict)
        
        # 如果文件已存在，先读取现有内容，保留注释
        if os.path.exists(filepath):
            with open(filepath, 'r', encoding='utf-8') as f:
                existing_content = f.read()
            # 添加文件开头的注释
            if '# This file is generated' not in existing_content:
                lines = ['# This file is generated by EnvManager', '']
                lines.append(content)
                content = '\n'.join(lines)
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        
        return True